### ISSUE TITLE
Umbraco 10 error: Could not load type Umbraco.Deploy.Core.IDiskEntityService

### ISSUE THREAD

**Issue by MichaelNielsenDK** [vendrhub/vendr-deploy#16]
I'm trying to upgrade an Umbraco Cloud site to v10, using this documentation
https://our.umbraco.com/documentation/Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/

The last thing in step 3 is to build and run locally, build is fine, but when running it, I get a WSOD with the following message
```
An error occurred while starting the application.
AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Vendr.Deploy.Composing.VendrDeployComponent Lifetime: Singleton ImplementationType: Vendr.Deploy.Composing.VendrDeployComponent': Could not load type 'Umbraco.Deploy.Core.IDiskEntityService' from assembly 'Umbraco.Deploy.Core, Version=10.0.1.0, Culture=neutral, PublicKeyToken=null'.)
```

Looks like IDiskEntityService has been moved from `Umbraco.Deploy.Core` to `Umbraco.Deploy.Infrastructure.Disk`. 
https://our.umbraco.com/documentation/Add-ons/Umbraco-Deploy/Upgrades/version-specific#code

Umbraco.Cms 10.0.0
Umbraco.Deploy.Cloud 10.0.1
Umbraco.Deploy.Contrib 10.0.0
Vendr 2.3.1
Vendr.Deploy 2.0.1

The raw exception details:
```
System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Vendr.Deploy.Composing.VendrDeployComponent Lifetime: Singleton ImplementationType: Vendr.Deploy.Composing.VendrDeployComponent': Could not load type 'Umbraco.Deploy.Core.IDiskEntityService' from assembly 'Umbraco.Deploy.Core, Version=10.0.1.0, Culture=neutral, PublicKeyToken=null'.)
     ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Vendr.Deploy.Composing.VendrDeployComponent Lifetime: Singleton ImplementationType: Vendr.Deploy.Composing.VendrDeployComponent': Could not load type 'Umbraco.Deploy.Core.IDiskEntityService' from assembly 'Umbraco.Deploy.Core, Version=10.0.1.0, Culture=neutral, PublicKeyToken=null'.
     ---> System.TypeLoadException: Could not load type 'Umbraco.Deploy.Core.IDiskEntityService' from assembly 'Umbraco.Deploy.Core, Version=10.0.1.0, Culture=neutral, PublicKeyToken=null'.
       at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
       at System.Reflection.RuntimeConstructorInfo.<get_Signature>g__LazyCreateSignature|19_0()
       at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
       at System.Reflection.RuntimeConstructorInfo.GetParameters()
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
       --- End of inner exception stack trace ---
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
       --- End of inner exception stack trace ---
       at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
       at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
       at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
       at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
       at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
       at Microsoft.Extensions.Hosting.HostBuilder.Build()
       at Umbraco.Cms.Web.Common.Hosting.UmbracoHostBuilderDecorator.Build()
       at Program.Main(String[] args) in C:\Work\SolutionName\src\ProjectName\Program.cs:line 9
```

**Comment by mattbrailsford** [comment]
Well that was awefully kind of them to move the interface without deprication 🤦‍♂️

I guess we won't be changing much for the v8/v9 builds so I'll have to release a new version compiled against v10

**Comment by mattbrailsford** [comment]
@MichaelNielsenDK there should be a Vendr Deploy v3 rc5 on the unstable feed shortly with it's dependencies updated. If you want to give that a try and see if it resolves things for you that would be great.

**Comment by MichaelNielsenDK** [comment]
@mattbrailsford 3.0.0-rc0005 solved the issue so I could proceed with the upgrade. It was successful the project is now running on v10 👍
