### ISSUE TITLE
Licensing problems when deploying

### ISSUE THREAD

**Issue by MichaelNielsenDK** [vendrhub/vendr-deploy#2]
Hi

Working on a new site, it's still in development. 

I installed Vendr Deploy locally, and pushed changes to Live. 

As I had already created a Store and everything else, I wanted to export these things to Live, by running echo > deploy-export in the local data folder to generate UDA files, but that failed with the exception below.

I then just manually saved the Store and everything else, which generated the UDA files, and I pushed those to Cloud. 

On Cloud though, the data extraction failed with the same message (below). 

Looks to be something with licensing perhaps (?)

Vendr 1.4.0-rc0065
Vendr.Deploy 0.1.0

```
EXCEPTION:

Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #1 failed for artifact umb://vendr-store/45a5e298251d40dda4cd5bdf17ba50f7.
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Work.WorkItems.DiskReadWorkItem.<Proceed>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.DiskReadWorkItem.<ExecuteAsyncSub>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.DiskReadWorkItem.<ExecuteAsync>d__15.MoveNext()

INNER:
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at Vendr.Core.Web.Licensing.LicensingDomainFingerprinter.GetFingerprint()
	   at Vendr.Core.Licensing.LicensingService.<GetLimitations>b__12_1(ILicense x)
	   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
	   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	   at Vendr.Core.Licensing.LicensingService.<GetLimitations>b__12_0()
	   at Umbraco.Core.Cache.HttpRequestAppCache.Get(String key, Func`1 factory)
	   at Vendr.Core.Web.Cache.UmbracoAppCache.Get(String cacheKey, Func`1 factory)
	   at Vendr.Core.Licensing.LicensingService.GetLimitations()
	   at Vendr.Core.Events.Validation.Handlers.Store.ValidateLicenseStoreUserGroupPermissions.Validate(ValidateStoreAllowUserRole evt)
	   at Vendr.Core.Events.Validation.ValidationEventHandlerBase`1.Handle(IEvent evt)
	   at Vendr.Core.Events.InProcEventDispatcher.Dispatch[T](IEnumerable`1 handlers, T evt)
	   at Vendr.Core.Events.EventBus.Dispatch[T](T evt)
	   at Vendr.Core.Models.AggregateBase`3.Validate(IValidationEvent validationEvent)
	   at Vendr.Core.Models.Store.AllowUserRole(String role)
	   at Vendr.Core.Models.Store.AllowUserRoles(IEnumerable`1 roles)
	   at Vendr.Core.Models.Store.SetAllowedUserRoles(IEnumerable`1 roles, SetBehavior setBehavior)
	   at Vendr.Deploy.Connectors.ServiceConnectors.VendrStoreServiceConnector.Pass1(ArtifactDeployState`2 state, IDeployContext context)
	   at Vendr.Deploy.Connectors.ServiceConnectors.VendrStoreServiceConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)
	   at Umbraco.Deploy.Connectors.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)
	   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
```

**Comment by mattbrailsford** [comment]
Hi @MichaelNielsenDK 

Hmm, it sounds like something in deploy runs outside of a web context and so the licensing service is unable to validate the license as it needs to access the current URL to validate the domain the site is running on.

It might be that we need to either update the license check to skip if it's not in a web context. I'll need to think about what the ramifications of this are though 🤔

**Comment by MichaelNielsenDK** [comment]
Ok, I've uninstalled Vendr.Deploy again and deleted all Vendr UDA files, to allow data extraction to function again. 

And for now I'll create a Store manually on environments. 

Let me know, when I can try and test it again.

**Comment by mattbrailsford** [comment]
Hi @MichaelNielsenDK 

I think I've managed to implement a fix for this. It got reported on the core Vendr issue tracker too and I've pushed an update to our unstable feed, Vendr 1.4.1-beta0076 if you wanted to give this a try and see if it resolved your problem too.

Matt

**Comment by MichaelNielsenDK** [comment]
It did 👍😊 Awesome 🤘
