### ISSUE TITLE
Unknown entity type error

### ISSUE THREAD

**Issue by MichaelNielsenDK** [vendrhub/vendr-deploy#9]
After installing Vendr Deploy and configuring Vendr, .uda files for the Vendr configuration is generated nicely enough. 

Afterwards though, I'm getting a deploy error that reads: Unknown entity type "vendr-currency"

I've checked in /umbraco/Deploy/Revision, the vendr-currency .uda file is there, it's also referenced from the vendr-country and vendr-store files, both as dependencies and because the currency is selected as default on these. 

Full stack trace is this:

```
EXCEPTION:

System.FormatException: Unknown entity type "vendr-currency".
   at Umbraco.Cms.Core.UdiParser.ParseInternal(String s, Boolean tryParse, Boolean knownTypes, Udi& udi)
   at Umbraco.Cms.Core.UdiParser.Parse(String s)
   at Umbraco.Cms.Infrastructure.Serialization.UdiJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Umbraco.Deploy.Infrastructure.Serialization.ArtifactJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Umbraco.Deploy.Infrastructure.Disk.DiskService.ReadArtifacts(String artifactDirectory)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.ExecuteAsyncSub(IWorkContext context, List`1 resume, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)
```

Umbraco 9.0.1
Vendr 2.0.3
Vendr Deploy 2.0.0

**Comment by mattbrailsford** [comment]
Hmm, I've got a funny feeling that maybe Umbraco Deploy may have changed. It always worries me when "knownTypes" is mentioned as this means there is potential that it's parsing only known UMBRACO types, which the currency obviously won't be.

I'll have to check with Andy at HQ to see if something might have changed.

**Comment by mattbrailsford** [comment]
Ok, spoke to Andy and there has indeed been a change in core whereby 3rd parties now need to register their custom UDI types like

    UdiParser.RegisterUdiType(VendrConstants.UdiEntityType.Store, UdiType.GuidUdi);

I've gone through and registered all the UDI types and an unstable build is currently in progress. I haven't been able to test it yet however as I need to re-set up my test environment for v9. If you want to give the unstable build a try it should be on our custom feed at https://nuget.outfield.digital/unstable/vendr/v3/index.json and you'll want the 2.0.1-beta004 build

**Comment by MichaelNielsenDK** [comment]
Hi Matt

That sounds awesome, I'll test it out later today.

**Comment by MichaelNielsenDK** [comment]
Hi Matt

That fixed it 👍

**Comment by mattbrailsford** [comment]
Perfect! I'll close this issue, but I'll wait towards the end of the week to push out a proper release just incase anything else pops up. Glad this ones resolved though. 👍

**Comment by MichaelNielsenDK** [comment]
Would you be able to release the 2.0.1-beta004 build as a stable build?

The build process fails on Umbraco Cloud when pushing up changes, because it can't find the package 
`error NU1102: Unable to find package Vendr.Deploy with version (>= 2.0.1-beta0004),,0 `
which makes sense, as they do not know your unstable feed as a source

I've asked Umbraco whether prereleases can be used, as long as they are accessible from the main nuget source with the -prerelease tag, or if it's possible to use other sources by using the `<RestoreSources>` or `<RestoreAdditionalProjectSources>` element in the .csproj file

I'll post an update when I hear from them.

**Comment by mattbrailsford** [comment]
Ooops, sorry my bad, forgot about this. Pushing out a release as we speak :+1:

**Comment by mattbrailsford** [comment]
@MichaelNielsenDK this should be available on NuGet now

**Comment by MichaelNielsenDK** [comment]
Awesome, thanks for that...

And I got an answer from Umbraco regarding additional package sources. It turns out there already is a nuget.config file at root level of the Cloud project, which I've totally missed 😅

In that you just add any addiotional sources
https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#package-source-sections 
Just for future reference, if anyone comes across this post with the same issue.
